version: "3.7"

services:
  hawkscan:
    image: stackhawk/hawkscan:latest
    command: stackhawk.yml stackhawk-travis.yml
    environment:
      - API_KEY=${HAWK_API_KEY}
      - APP_ID=${APP_ID}
      - APP_ENV="${APP_ENV:-Travis CI}"
      - HOST=${HOST:-http://vuln-proxy:8020}
    volumes:
      - .:/hawk

  vuln-proxy:
    logging:
      driver: none

  vuln-django:
    logging:
      driver: none
