
stages:
  - build
  - test
  - deploy
  - hawkscan

#variables:
#  DAST_VERSION: 1

hawkscan:
  stage: hawkscan
  services:
    - docker:19.03.1-dind
  image:
    name: "stackhawk/hawkscan:latest"
  variables:
    GIT_STRATEGY: fetch
  allow_failure: true
  script:
    - env
    - pwd
    - shawk $HAWKSCAN_ARGS
#  artifacts:
#    reports:
#      dast: gl-dast-report.json
#  only:
#    refs:
#      - branches
#    variables:
#      - $GITLAB_FEATURES =~ /\bdast\b/
#  except:
#    variables:
#      - $DAST_DISABLED
#      - $DAST_DISABLED_FOR_DEFAULT_BRANCH && $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
