include:
  local: HAWKSCAN_LOCAL.gitlab-ci.yml

variables:
  HAWKSCAN_ARGS: "stackhawk.yml stackhawk-gitlab-heroku.yml"

stages:
  - test
  - build
  - deploy
  - hawkscan

docker-build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - env
    - docker build -t vuln_django:latest .

deploy-heroku:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=vuln-django --api-key=$HEROKU_STAGING_API_KEY
