version: 2.1

orbs:
  stackhawk: stackhawk/stackhawk@1.0.1
  secrethub: secrethub/cli@1.1.0

workflows:
  build-and-scan:
    jobs:
      - stackhawk/hawkscan-local:
          configuration-files: ./stackhawk.yml ./stackhawk-circleci.yml
          docker-network: scan_net
          app-id: a629eeae-4bb9-4918-b3eb-bb141b4e8918
          pre-steps:
            - secrethub/env-export:
                var-name: HAWK_API_KEY
                secret-path: webinar/appsec/stackhawk/api_key
          steps:
            - run:
                name: Build Vulnarable Django
                command: docker build -t vuln_django:latest .
            - run:
                name: Create scan_net Network
                command: docker network create scan_net
            - run:
                name: Run Vulny Django
                command: docker run --detach --network scan_net --name vuln-django --rm vuln_django:latest
