version: 2.1

orbs:
  stackhawk: stackhawk/stackhawk@dev:alpha

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build the vulnerable Django app
          command: docker build -t vuln_django:latest .
      - run:
          name: Create a scan network so we can address containers by name
          command: docker network create scan_net
      - run:
          name: Run the vulnerable Django app
          command: docker run --detach --network scan_net --name vuln-django --rm vuln_django:latest
      - stackhawk/hawkscan:
          api-key: "${TEST_API_KEY}"
          auth-endpoint: https://auth.test.stackhawk.com
          results-endpoint: https://api.test.stackhawk.com/api/v1
          configuration-files: ./stackhawk.yml ./stackhawk-circleci.yml
          docker-network: scan_net
          app-id: 2bd303e8-a0d0-46b6-8306-5fc552d79d6a
          host: http://vuln-django:8020
          env: "${CIRCLE_BRANCH}"
