# dev.yml -- build and run the turnkey Django container with SQLite
version: '3.7'

services:
  vuln-django:
    build:
      args:
        - SERVER_PORT=${SERVER_PORT:-8020}
    environment:
      - SERVER_PORT=${SERVER_PORT:-8020}
    ports:
      - ${SERVER_PORT:-8020}:${SERVER_PORT:-8020}
