version: "3.2"

services:
  vuln-django:
    image: vuln_django
    container_name: vuln-django
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - SERVER_PORT=${SERVER_PORT:-8020}
        - DATABASE=mysql
    environment:
      - SERVER_PORT=${SERVER_PORT:-8020}
    ports:
      - ${SERVER_PORT:-8020}:${SERVER_PORT:-8020}
    entrypoint:
      - /opt/app/start-server.sh

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
    ports:
      - 3306:3306

